version: "3.8"
services:
  app:
    image: zae0i/fintech:latest
    container_name: fintech-app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1105
      MYSQL_DATABASE: fintech
      MYSQL_USER: fintech
      MYSQL_PASSWORD: 1105
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
